spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lbs?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 12345
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
server:
  port: 8081