spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lbs?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 12345
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
#    show-sql: true
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: GMT+8
server:
  port: 8081

lbs:
  image-path: file:/C:/temp/
  upload-path: C:\temp\
