spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lbs?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 12345
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
server:
  port: 8081
